/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minifyjpeg.h"
#include "magickminify.h"
#include <stdio.h>

FileTransfer *
getfile_1_svc(FileTransfer arg1, struct svc_req *rqstp) {
	static FileTransfer result;

	/*
	 * insert server code here
	 */

	magickminify_init();

	ssize_t dest_len;

	printf("Receive %d\n", arg1.fileHandler.fileHandler_len);

	result.fileHandler.fileHandler_val = (char*) magickminify(arg1.fileHandler.fileHandler_val,
			arg1.fileHandler.fileHandler_len, &dest_len);

	result.fileHandler.fileHandler_len = dest_len;
	printf("Output %ld\n", dest_len);
	return &result;
}
