/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minifyjpeg.h"


void
minifyjpeg_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	CharTransferData result_1;
	CharTransferData getfile_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, MINIFYJPEG_PROG, MINIFYJPEG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = getfile_1(getfile_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	minifyjpeg_prog_1 (host);
exit (0);
}
